import type { CrmLead } from "@/lib/crm/types";

/** Fixtures only for UI preview / screenshots when Supabase is unavailable. */
export const CRM_DEMO_LEADS: CrmLead[] = [
  {
    id: 1,
    company_name: "Berg Barbearia",
    phone: "(86) 3236-9141",
    email: null,
    address: "Av. Vilmary, 2941 - São Cristóvão, Teresina",
    niche: "Barbearia",
    city: "Teresina",
    status: "contacted",
    notes: null,
    estimated_value: null,
    follow_up_at: null,
    website_url: null,
    google_maps_url: "https://maps.google.com/?q=Berg+Barbearia",
    rating: 4.8,
    review_count: 272,
    source: "google_places",
    slug: "berg-barbearia",
    visit_count: 0,
    site_status: "not_generated",
    site_source: null,
    site_brief: null,
    ai_diagnosis: null,
    ai_outreach: null,
    deleted_at: null,
    created_at: "2026-09-10T12:00:00.000Z",
    updated_at: "2026-09-12T12:00:00.000Z",
  },
  {
    id: 2,
    company_name: "Studio Norte Estética",
    phone: "(86) 99811-2200",
    email: "contato@studionorte.com",
    address: "Rua Coelho Rodrigues, 120",
    niche: "Estética",
    city: "Teresina",
    status: "new",
    notes: null,
    estimated_value: 890,
    follow_up_at: null,
    website_url: null,
    google_maps_url: null,
    rating: 4.6,
    review_count: 88,
    source: "manual",
    slug: "studio-norte-estetica",
    visit_count: 0,
    site_status: "not_generated",
    site_source: null,
    site_brief: null,
    ai_diagnosis: null,
    ai_outreach: null,
    deleted_at: null,
    created_at: "2026-09-14T09:00:00.000Z",
    updated_at: null,
  },
  {
    id: 3,
    company_name: "Café do Centro",
    phone: "(86) 3222-4411",
    email: null,
    address: "Centro",
    niche: "Café",
    city: "Teresina",
    status: "hot",
    notes: "Visita marcada",
    estimated_value: 1200,
    follow_up_at: "2026-09-20T15:00:00.000Z",
    website_url: null,
    google_maps_url: null,
    rating: 4.2,
    review_count: 41,
    source: "foursquare",
    slug: "cafe-do-centro",
    visit_count: 2,
    site_status: "ready",
    site_source: "uploaded",
    site_brief: null,
    ai_diagnosis: { dorPrincipal: "Poucas reservas online", prioridade: "alta" },
    ai_outreach: { mensagem: "Oi! Vi o Café do Centro no Maps..." },
    deleted_at: null,
    created_at: "2026-09-08T10:00:00.000Z",
    updated_at: "2026-09-15T10:00:00.000Z",
  },
  {
    id: 4,
    company_name: "Auto Peças Lima",
    phone: null,
    email: null,
    address: null,
    niche: "Automotivo",
    city: "Timon",
    status: "proposal",
    notes: "Enviar proposta de site",
    estimated_value: 1500,
    follow_up_at: "2026-09-18T14:00:00.000Z",
    website_url: "https://example.com",
    google_maps_url: null,
    rating: 3.9,
    review_count: 19,
    source: "maps2sheets",
    slug: "auto-pecas-lima",
    visit_count: 0,
    site_status: "not_generated",
    site_source: null,
    site_brief: null,
    ai_diagnosis: null,
    ai_outreach: null,
    deleted_at: null,
    created_at: "2026-09-05T11:00:00.000Z",
    updated_at: "2026-09-11T11:00:00.000Z",
  },
  {
    id: 5,
    company_name: "Clínica Vida+",
    phone: "(86) 3300-1000",
    email: "recepcao@clinicavidamais.com",
    address: "Jóquei",
    niche: "Clínica",
    city: "Teresina",
    status: "won",
    notes: "Fechado — plano anual",
    estimated_value: 2400,
    follow_up_at: null,
    website_url: null,
    google_maps_url: null,
    rating: 4.9,
    review_count: 310,
    source: "google_places",
    slug: "clinica-vida-mais",
    visit_count: 12,
    site_status: "published",
    site_source: "uploaded",
    site_brief: null,
    ai_diagnosis: null,
    ai_outreach: null,
    deleted_at: null,
    created_at: "2026-08-20T08:00:00.000Z",
    updated_at: "2026-09-01T08:00:00.000Z",
  },
  {
    id: 6,
    company_name: "Pet House",
    phone: "(86) 99900-1122",
    email: null,
    address: "Fátima",
    niche: "Pet shop",
    city: "Teresina",
    status: "lost",
    notes: "Sem orçamento agora",
    estimated_value: null,
    follow_up_at: null,
    website_url: null,
    google_maps_url: null,
    rating: 4.0,
    review_count: 55,
    source: "manual",
    slug: "pet-house",
    visit_count: 0,
    site_status: "not_generated",
    site_source: null,
    site_brief: null,
    ai_diagnosis: null,
    ai_outreach: null,
    deleted_at: null,
    created_at: "2026-08-01T08:00:00.000Z",
    updated_at: "2026-08-15T08:00:00.000Z",
  },
  {
    id: 7,
    company_name: "Padaria São José",
    phone: "(86) 3211-7788",
    email: null,
    address: "Zona Sul",
    niche: "Padaria",
    city: "Teresina",
    status: "new",
    notes: null,
    estimated_value: null,
    follow_up_at: null,
    website_url: null,
    google_maps_url: null,
    rating: 4.5,
    review_count: 140,
    source: "openstreetmap",
    slug: "padaria-sao-jose",
    visit_count: 0,
    site_status: "not_generated",
    site_source: null,
    site_brief: null,
    ai_diagnosis: null,
    ai_outreach: null,
    deleted_at: null,
    created_at: "2026-09-15T16:00:00.000Z",
    updated_at: null,
  },
  {
    id: 8,
    company_name: "Odonto Smile",
    phone: "(86) 98877-6655",
    email: "agenda@odontosmile.com",
    address: "Ilhotas",
    niche: "Dentista",
    city: "Teresina",
    status: "replied",
    notes: "Pediu retorno na sexta",
    estimated_value: 1800,
    follow_up_at: "2026-09-19T10:00:00.000Z",
    website_url: null,
    google_maps_url: null,
    rating: 4.7,
    review_count: 96,
    source: "google_places",
    slug: "odonto-smile",
    visit_count: 1,
    site_status: "generating",
    site_source: null,
    site_brief: null,
    ai_diagnosis: { dorPrincipal: "Agenda lotada sem canal digital", prioridade: "média" },
    ai_outreach: { mensagem: "Olá, Odonto Smile! ..." },
    deleted_at: null,
    created_at: "2026-09-09T13:00:00.000Z",
    updated_at: "2026-09-13T13:00:00.000Z",
  },
];
